### ISSUE TITLE
Error from server (NotFound): deployments.extensions "xxxxxx" not found (pipeline got response fail, but the deployment is successful)

### ISSUE THREAD

**Issue by sstshenshutao** [GoogleCloudPlatform/github-actions#104]
### TL;DR

in 'github-actions/example-workflows/gke/.github/workflows/gke.yml'
line 77-78:
```
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$IMAGE
```
you use the pipeline, you can't use 'deployment/$IMAGE' to get back.
so it will be a pipeline error, and you got 
"Error from server (NotFound): deployments.extensions "xxxxxx" not found"
**Expected behavior**

no errors with 'deploy', if I change it to 'get deployments', I got
```
deployment.apps/gke-test configured
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
gke-test   0/1     1            0           20m
```
and finished, so it is the only problem.
**Observed behavior**

### Reproduction

**Action YAML**

```yaml
# Paste your complete GitHub Actions YAML here, removing
# any sensitive values.
```

**Repository**

 

**Additional information**

**Comment by Binyamse** [comment]
same here, deployment is ok but the build fails in actions

**Comment by sstshenshutao** [comment]
hi, 
I know where is the small deviation: "The deployment name is not equal to the {IMAGE}"
if you try to name the deployment as "static-site", you can get the right answer.

You can also use this to avoid the name-deviation: 

Add a DEPLOYMENT_NAME variable in env: 
> env:
>   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
>   GKE_CLUSTER: cluster-1   # TODO: update to cluster name
>   GKE_ZONE: us-central1-c  # TODO: update to cluster zone
>   IMAGE: static-site
>   **DEPLOYMENT_NAME: xxx-server**  # which is the same name of your **DEPLOYMENT**, not your docker image name!!
> 

and then change the line 78:

>         kubectl rollout status deployment/$IMAGE

to 

>        kubectl rollout status deployment/$DEPLOYMENT_NAME

have fun with k8s~

**Comment by sanishtj** [comment]
Same issue for me. `kubectl rollout status` is already `deployment/$DEPLOYMENT_NAME`

**Comment by sanishtj** [comment]
And I think I know what's my issue. I have a custom namespace created and my deployments go there. So below command works for me, 

`kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NameSpace`

I created an env var for Namespace
