### ISSUE TITLE
Include alpha and beta components out of the box

### ISSUE THREAD

**Issue by vorburger** [GoogleCloudPlatform/github-actions#106]
For [FINERACT-970](https://jira.apache.org/jira/browse/FINERACT-970), I am (need to) use `gcloud beta builds triggers run XYZ` in [my YAML using this GitHub Action](https://github.com/apache/fineract/blob/04d3ce673c974d92a31c6bb35a7eb560ddfc376d/.github/workflows/fineract.dev.yaml), but this [currently fails](https://github.com/apache/fineract/runs/681546103?check_suite_focus=true) due to "beta components" not being installed - and their automatic installation apparently not "just" working out of the box.

I'll see if I can fix this just by adding `--quiet`, but would there be any downside to just always including "beta components" in the image of this action? -- Or could/should `--quiet` perhaps by made true by default in this image?

#103 seems to be somewhat related to this.

**Comment by sethvargo** [comment]
Can you run `gcloud components install beta` in your script? The problem is that the alpha/beta components are just as large as the main one, so installing one or both doubles or triples install time.

**Comment by vorburger** [comment]
@sethvargo yup, just figured that (before reading this), and done so in https://github.com/apache/fineract/pull/901 - that [seems to works great, see here](https://github.com/apache/fineract/runs/681579008?check_suite_focus=true). Just FTR to future reader: Using --quiet didn't work (https://github.com/apache/fineract/pull/900).

I'm closing this. (Re-open if you think there is still any follow-up action required.)
