### ISSUE TITLE
can't build image with cloud-run

### ISSUE THREAD

**Issue by adsee42** [GoogleCloudPlatform/github-actions#130]
### Question

I'm using [this action](https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml) to build and push my image, but got error below at step `- name: Build`

```
Run gcloud builds submit \
Creating temporary tarball archive of 13 file(s) totalling 11.3 KiB before compression.
Some files were not included in the source upload.

Check the gcloud log [/home/runner/.config/gcloud/logs/2020.07.06/05.12.34.092568.log] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [.] to [gs://***_cloudbuild/source/1594012354.217488-352bbe5e5f6542d7a3f55b23ea39924d.tgz]
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid image name "gcr.io/***/***:ef88a8...github_sha": could not parse reference: gcr.io/***/***:ef88a8...github_sha
##[error]Process completed with exit code 1.
```

I can't find any information about this error with Google.

How can I solve this?

**Comment by bharathkkb** [comment]
Hi @adsee42! That image name does seem a bit off. It should be something like `gcr.io/fooproject/helloworld-nodejs: d72625cc005c69b3872335beb86ce20dba117c1d `. 

However yours seems to have `github_sha` string appended to the end instead of the actual SHA. Have you made any changes to the example yml and if you have, could you share it so I can try to reproduce?

**Comment by adsee42** [comment]
Hi @bharathkkb ! Thanks for response.
I found out the problem is with the dockerfile path.
My dockerfile is not in the root, so I needed to specify its path after `gcloud builds submit`.

The original `github_sha` is too long so I modified it....
The real value is just like your example.
