### ISSUE TITLE
setup-gcloud: Using the project_id from the service_account_key.

### ISSUE THREAD

**Issue by treeder** [GoogleCloudPlatform/github-actions#132]
### TL;DR

Have a way (or by default) to use the project_id from the service_account_key.

### Design

The service_account_key json should have a `project_id` value in it and it would be nice to be able to use that rather than having to pass in a separate project_id. Either by default or a flag to ask the action to use it. This would avoid having to have a separate secret for this.

**Comment by sethvargo** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/github-actions/issues/114 - please see the rationale there. Thanks!

**Comment by treeder** [comment]
Yep, this is a dupe! I'll respond there.
