### ISSUE TITLE
Safe to store keyfile.json in secrets?

### ISSUE THREAD

**Issue by Stegosource** [GoogleCloudPlatform/github-actions#134]
### Question

The [README](https://github.com/GoogleCloudPlatform/github-actions/blob/bbe627fd2161088c7892b9daf1ad4417dd1c7dec/example-workflows/cloud-build/README.md) says you should save your service account keyfile contents as a repository secret, but GitHub's secrets documentation explicitly states [you should not store JSON in secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#naming-your-secrets)

> To help ensure that GitHub redacts your secret in logs, avoid using structured data as the values of secrets. For example, avoid creating secrets that contain JSON or encoded Git blobs.

Is it still safe to do so?

**Comment by sethvargo** [comment]
Yes, you can also base64 encode the JSON file, but that doesn't increase/decrease the chances it will appear in logs.

**Comment by Stegosource** [comment]
Yeah, so I dont understand why you say it's safe while GH advises against it. Do you have anything else you could point me to? Not trying to be difficult, but I try to take security as seriously as possible.

**Comment by sethvargo** [comment]
You need some kind of authentication to GCP, and the most common authentication mechanism is service account keys. Those keys happen to be in a JSON format. The other alternative is to use custom runners hosted on GCP, and then leverage the machine identity to make the API calls, obviating the need to store a credential.

GitHub does a primitive string match to scrub logs, so alterations to the string (padding, spaces, ordering), would cause the log to not be scrubbed. If you don't log your credential, this won't be an issue anyway.

**Comment by Stegosource** [comment]
Yeah. I've done deploys to AWS by using access keys and access key secrets for an IAM role. But it doesn't look like GCP provides that sort of option, or some sort of CLI arguments rather than the keyfile.json.

I guess I'll go with your suggestion. Thanks for the time :)

**Comment by sethvargo** [comment]
We support API keys, but they are limited to 1hr and likely not a good solution for this use case.

**Comment by Stegosource** [comment]
Im going to go ahead and close this. From what I found online, the base64 encoded keyfile.json contents seems to be the way to go. Thanks @sethvargo

**Comment by ralyodio** [comment]
How do I base64 encode/decode the json file?

**Comment by AustinGil** [comment]
You can use any encoder. First one I found from DuckDuckGo was https://www.base64encode.org/

**Comment by sethvargo** [comment]
Please do not paste your Service Account Key JSON into random websites. These files are like passwords and should be treated as such.

On Unix systems (Linux, Mac), you can do the following:

```shell
cat keyfile.json | base64 -w0
```

On Windows, you can either use WSL and run the command above, or use Powershell:

```pwsh
[convert]::ToBase64String((Get-Content -path "keyfile.json" -Encoding byte))
```

**Comment by janKir** [comment]
What's the reason to store it as base64?

**Comment by LewisCowlesMotive** [comment]
to avoid having quoted characters and control sequence (for GitHub yaml).
