### ISSUE TITLE
Passing arguments to gcloud builds submit

### ISSUE THREAD

**Issue by tjdam** [GoogleCloudPlatform/github-actions#150]
Hi, sorry for the newbie question, but how do I pass environment variables to glcloud builds submit?
I looked in manual and that option doesn't seem to exist which seems odd. Everything in should be hardcoded?

**Comment by bharathkkb** [comment]
Hi @tjdam 

You can use [substitutions](https://cloud.google.com/sdk/gcloud/reference/builds/submit#--substitutions) for passing values dynamically with gcloud builds submit.

**Comment by bharathkkb** [comment]
Hi @tjdam 
Closing this out, feel free to reopen if needed.
