### ISSUE TITLE
Question: Can GOOGLE_CREDENTIALS be used to authenticate?

### ISSUE THREAD

**Issue by charlex** [GoogleCloudPlatform/github-actions#165]
### Question

Can a (1) JSON key, or (2) a file path be used in GOOGLE_CREDENTIALS to authenticate with gcloud?

**Comment by averikitsch** [comment]
Workflow field `service_account_key` for the setup-gcloud action and `credentials` for other actions needs to be the JSON key. The setup-gcloud action field `export_default_credentials` will create a temporary file with this JSON key and set the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to this file. This environment variable is used to authenticate other Google services, for more info see [Finding crednetials automatically](https://cloud.google.com/docs/authentication/production#automatically).

**Comment by charlex** [comment]
Thank you.
