### ISSUE TITLE
Latest commit causing action to fail

### ISSUE THREAD

**Issue by mingles** [GoogleCloudPlatform/github-actions#21]
Hi there,

I'm using this to authenticate and deploy my app onto Google Cloud Run. Snippet below is from my github workflow file:
```
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
```

It's started immediately failing, I believe due to the latest commit. I re-ran passed workflows from yesterday which now fail. The error on these and all new workflows is:

```
Run GoogleCloudPlatform/github-actions/setup-gcloud@master
/home/runner/work/_actions/GoogleCloudPlatform/github-actions/master/setup-gcloud/dist/index.js:7860
        methods.forEach(function(m) {
        ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
##[error]Node run failed with exit code 1
```

Any ideas?

**Comment by wktk** [comment]
A syntax error seems to be causing this issue.

https://github.com/GoogleCloudPlatform/github-actions/blob/0c32120a9a2dda7fb9b392e6c3b90fa413b4642e/setup-gcloud/dist/index.js#L7853-L7863

Checking out an older commit worked for me as a workaround.

```yaml
- uses: GoogleCloudPlatform/github-actions/setup-gcloud@4d8f7a1
```

**Comment by stephenashank** [comment]
@mingles @wktk Thanks for pointing this out, let me know if you have any other issues.

**Comment by wktk** [comment]
@stephenashank Thank you for the update!
Unfortunately, it is still failing for me.  It seems that we need to rebuild `setup-gcloud/dest/index.js`.

```
 /home/runner/work/_actions/GoogleCloudPlatform/github-actions/master/setup-gcloud/dist/index.js:9124
          })(b64chars);
           ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
##[error]Node run failed with exit code 1
```

**Comment by craigdbarber** [comment]
A quick postmortem revealed this was caused by eslint not playing nice with the code ncc was generating. I've reverted the manual changes to the dist/ folder and re-ran npm build.  I will follow up with a PR removing eslint from scripts and adding an IT which will ensure something like this doesn't get released again.
