### ISSUE TITLE
GitHub-hosted runners include Google Cloud SDK

### ISSUE THREAD

**Issue by zxyle** [GoogleCloudPlatform/github-actions#28]
When I read [Github Documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1604-lts), I find Google Cloud SDK available in GitHub-hosted virtual environments. So, I tried write in my [workflow](https://github.com/BoardCAM/BoardCAM.org/blob/master/.github/workflows/pythonapp.yml), It's work very well. 
Then the question comes, Why do we need this action?

**Comment by craigdbarber** [comment]
This action allows users to install a specific version of the SDK. You'll note that version 272 is what's installed by default, however as of this posting 274 is the latest version.

**Comment by yashsaini77** [comment]
Can anyone please tell that if we can store user id and password instead of service account of gcp account as secrets to be used in git actions ?
