### ISSUE TITLE
Why not use "kubectl apply -k" ?

### ISSUE THREAD

**Issue by inductor** [GoogleCloudPlatform/github-actions#29]
In the following line you install kustomize to build your kustomize templates but since kubectl 1.14 they started kustomize integration. is there any reasons why you don't use it?

https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gke/.github/workflows/gke.yml#L75-L85

**Comment by msokk** [comment]
kubectl integration does not have `edit set` functionality unfortunately
