### ISSUE TITLE
"gke-test" hardcoded in gke.yml

### ISSUE THREAD

**Issue by kaikue** [GoogleCloudPlatform/github-actions#39]
On line 86 of the gke example workflow:
https://github.com/GoogleCloudPlatform/github-actions/blob/99d5219b2ca42b90042bd5bfdc39cc5ece899a4f/example-workflows/gke/.github/workflows/gke.yml#L86

If this isn't changed it causes the error `Error from server (NotFound): deployments.extensions "gke-test" not found` during the Deploy step. I think `gke-test` should be changed to `$IMAGE` here, so that it respects the environment variable.

**Comment by averikitsch** [comment]
`deployment/gke-test ` refers to the name of the deployment
```
# deployment.yml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gke-test
...
```
 and not the name of the image. The name of the deployment doesn't need to be the same as the image.

**Comment by jainrounak6** [comment]
I'm getting error  InvaildImageName
Name:                  Status:                                                Summary
gke-test        "InvaildImageName"                gke-test:asia.gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

**Comment by averikitsch** [comment]
@jainrounak6 Please open a new issue with notes on where you are seeing this error and what you have changed in the file. Thanks!
