### ISSUE TITLE
GCP Installing Component Docker Version is outdated

### ISSUE THREAD

**Issue by prototypeAi** [GoogleCloudPlatform/github-actions#40]
This is probably the wrong place but if i want to install a component which currently doesnt exist in the supplied gcp sdk 
i.e: 
` gcloud auth configure-docker
          gcloud components install docker-credential-gcr
          docker-credential-gcr configure-docker`

I get an error that my docker version is outdated. (Only supported docker version x >= 10.5) 

I fixed this by adding another step:
` - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce` 

However this approach cost around 1,5 minutes of time. Which is not really optimal. 

I think this issue involves this one: 
https://github.community/t5/GitHub-Actions/What-really-is-docker-3-0-6/td-p/30752

Maybe you have a better idea how to fix this. 

Cheers

**Comment by craigdbarber** [comment]
Hi @prototypeAi Unfortunately we don't control the default version of Docker installed on the runner. To specify a custom one you would have to take the approach you mentioned, or else use the setup-docker action which does exactly the same thing under the hood. 

An alternative you might consider would be using GCP's cloud build to build and publish your container image for you. This would alleviate the overhead of setting up the runner's env, and should be quicker than installing docker. Here's an example:

```
run:
  gcloud builds submit --tag gcr.io/$PROJECT_ID/$IMAGE_NAME .
``` 

More info: https://cloud.google.com/cloud-build/docs/quickstart-docker
