### ISSUE TITLE
Cloud Run example is duplicated

### ISSUE THREAD

**Issue by mightyguava** [GoogleCloudPlatform/github-actions#46]
There are 3 copies of `cloud-run.yml`, and they all differ slightly. Which one's the real one?

https://github.com/GoogleCloudPlatform/github-actions/blob/9025ea6d30e6ede8a4ef3673e9c694e7359e4f56/example-workflows/cloud-run/cloud-run.yml
https://github.com/GoogleCloudPlatform/github-actions/blob/9025ea6d30e6ede8a4ef3673e9c694e7359e4f56/example-workflows/cloud-run/workflows/cloud-run.yml
https://github.com/GoogleCloudPlatform/github-actions/blob/9025ea6d30e6ede8a4ef3673e9c694e7359e4f56/example-workflows/cloud-run/.github/workflows/cloud-run.yml

**Comment by averikitsch** [comment]
Hi, please see the master branch for the latest [copy](https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml).

**Comment by mightyguava** [comment]
Yes. The master branch has 3 copies

**Comment by averikitsch** [comment]
I apologize, the fix is in #47
