### ISSUE TITLE
.p12 service account keys PyOpenSSL errors

### ISSUE THREAD

**Issue by bonham000** [GoogleCloudPlatform/github-actions#59]
Hi, I've been trying to set this up and have been unsuccessful for several hours now. I've followed the documentation exactly like this:

```
# Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
```

Where the two secrets are provided in the environment using GitHub Secrets and the `GOOGLE_APPLICATION_CREDENTIALS` is the `base64` encoding of the JSON secret key created for the service account. The service account is activated and I believe it has the right permissions, but the actions workflow fails every time with:

```
/bin/tar xz -C /home/runner/work/_temp/d808259f-fc3f-4628-8c8f-d8d611055a81 -f /home/runner/work/_temp/097fc0ed-8610-4d65-8481-6ae4de38eb3b
gcloud auth activate-service-account $GOOGLE_SERVICE_ACCOUNT_EMAIL --key-file=/tmp/tmp-7195qsuIHwy3Vvhx
WARNING: .p12 service account keys are not recomended unless it is necessary for backwards compatability. Please switch to a newer .json service account key for this account.
ERROR: (gcloud.auth.activate-service-account) PyOpenSSL is not available. If you have already installed PyOpenSSL, you will need to enable site packages by setting the environment variable CLOUDSDK_PYTHON_SITEPACKAGES to 1. If that does not work, see https://developers.google.com/cloud/sdk/crypto for details or consider using .json private key instead.
##[error]The process 'gcloud' failed with exit code 1
```

I've even tried installing `PyOpenSSL` but got the same error. I've also looked at the other 2 or 3 closed issues here with similar errors but didn't find any solution yet.

I'm not sure if I missed some documentation steps, but I am really at a dead-end to figure out what I am missing. Thanks for any advice you may have!

**Comment by craigdbarber** [comment]
Hi @bonham000 thanks for reaching out. Please take a look at our documentation regarding the action's inputs: https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud#inputs
Specifically, make sure your SA Key is base64 encoded. Let me know if that helps.

**Comment by bonham000** [comment]
It definitely is, I figured it out. In the `env` setup in GitHub Actions you cannot reference environment variables, you have to reference secrets directly. For instance

```
env:
   service_account_key: $GOOGLE_SERVICE_ACCOUNT_KEY
```

Will not work but

```
env:

```
env:
   service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
```

Will work.

If anyone else runs into similar problems, I found [this article](https://medium.com/better-programming/publish-your-cloud-run-app-with-github-actions-6c18ff5c5ee4) which provides a great walkthrough for the entire setup process.
