### ISSUE TITLE
Missing permission for cloud run build

### ISSUE THREAD

**Issue by gjgd** [GoogleCloudPlatform/github-actions#62]
Using the four permissions mentioned in the README [here](https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows/cloud-run#setup) my gcloud build is failing:

```
gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

(...)

ERROR: (gcloud.builds.submit) HTTPError 403: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>*** does not have storage.objects.get access to 43928094282.cloudbuild-logs.googleusercontent.com/log-6a7876f9-9f49-478b-b055-12c290cc3c84.txt.</Details></Error>
##[error]Process completed with exit code 1.
```

**Comment by gjgd** [comment]
Solved by adding the "Cloud Build Editor permission"

<img width="536" alt="Screenshot 2020-02-27 at 14 10 45" src="https://user-images.githubusercontent.com/7913565/75420913-af8f5380-596b-11ea-8230-98060cbec728.png">

**Comment by sulunemre** [comment]
This solution worked for me: https://github.com/GoogleCloudPlatform/github-actions/issues/49#issuecomment-581783969

I think docs should be updated

**Comment by gjgd** [comment]
Reopening, as a reminder to update the README

**Comment by tnguyen14** [comment]
I have added the "Cloud Build Editor" role to my service account, but I'm still seeing this error.

Is there something else I might be missing?

**Comment by tnguyen14** [comment]
So I tried giving Storage Object Viewer and Storage Admin permission, but it didn't work. I then added the generic "Viewer" role and that did the trick.

**Comment by whyboris** [comment]
This is incredibly frustrating -- why doesn't `gcloud builds submit` check permissions before running through the build process?

My build process takes close to 10 minutes before I find out I don't have enough permissions. Why waste everyone's time? Is Google making money from running the build?

**Comment by xSAVIKx** [comment]
This indeed is very frustrating that we have to give the SA `Viewer` role in order to submit builds. Is there any other more restrictive role that can be used?
