### ISSUE TITLE
gcloud.builds.submit 

### ISSUE THREAD

**Issue by SanketDG** [GoogleCloudPlatform/github-actions#75]
I am running the sample workflow and I am not able to get it working

Build step output
```
ERROR: (gcloud.builds.submit) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
```

I thought the auth is automatically inferrred from the gcloud setup step, do I need to do anything additional here?

**Comment by sethvargo** [comment]
Can you share your `action.yaml` please? Did you provide a service account credential via a GitHub secret?

**Comment by SanketDG** [comment]
Right, I wasn't aware that the service account credentials needed to be passed too! Thanks.

I now am on a other issue, 

```
Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.
```

Why do I need to set a env variable for my Dockerfile?

Also it seems like when I directly visit the logs of my Cloud Run dashboard in GCP, I see a log statement from my application code, which means the application probably started fine!

**Comment by sethvargo** [comment]
> Right, I wasn't aware that the service account credentials needed to be passed too! Thanks.

You always need to pass service accounts unless your using custom runners deployed on GCP.

> Why do I need to set a env variable for my Dockerfile?

Could you share the code? That error is coming from Cloud Run, not this action. What happens if you run `gcloud run deploy` yourself?

**Comment by bharathkkb** [comment]
Hi @SanketDG 
I had previously encountered this issue when the application inside my container was not listening on port 8080 and I had not overridden the default port with the  --port flag. PTAL [1] & [2]
[1]: https://cloud.google.com/run/docs/reference/container-contract#port
[2]: https://cloud.google.com/run/docs/configuring/containers#configure-port

**Comment by SanketDG** [comment]
Interesting.

I assume that the current documentation for example workflows was intended for people who are experienced with GCP and thus know how to setup auth workflows.

I was setting the whole thing up for the first time and I had no idea about these things.

>>  overridden the default port with the --port flag

Is this to be done in the `deploy` command? @bharathkkb

**Comment by bharathkkb** [comment]
Hi @SanketDG 
> Is this to be done in the `deploy` command? @bharathkkb

yes, it is an available parameter in [gcloud >=275.0.0](https://cloud.google.com/sdk/docs/release-notes#cloud_run_5). More info about that flag here here: https://cloud.google.com/sdk/gcloud/reference/run/deploy#--port

**Comment by sethvargo** [comment]
Hi @SanketDG 

Did that help solve your issue?

**Comment by SanketDG** [comment]
Yes , it did.

Thanks @sethvargo @bharathkkb
