### ISSUE TITLE
gcloud.auth.activate-service-account Authentication Error

### ISSUE THREAD

**Issue by mcgizzle** [GoogleCloudPlatform/github-actions#76]
This workflow was working fine until day.

Nothing has been changed but I am now receiving this error:

```
ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: invalid_grant: Invalid JWT Signature.
```

**Comment by sethvargo** [comment]
Hi @mcgizzle 

Could you please share your `action.yml` file?

**Comment by mcgizzle** [comment]
Thanks for the quick reply!

closing as it was actually an issue on my end (key had been rotated). 

Sorry!
