### ISSUE TITLE
Need of using base64 missing in GKE example documentation

### ISSUE THREAD

**Issue by Pitazzo** [GoogleCloudPlatform/github-actions#88]
### TL;DR

In the GKE example readme file should be clarified that the GKE_SA_KEY has to contain the **base64** enconding of the JSON key file and not the plain file

**Comment by sethvargo** [comment]
Hi @Pitazzo - thank you for opening an issue. As of February 19, 2019 (https://github.com/GoogleCloudPlatform/github-actions/commit/b060325aeba4554d6e9983f16f84411c8c838e13), the action handles both base64-encoded and non-base64-encoded credentials.

Are you experiencing an issue with the action? Could you please complete the template and provide an `action.yml` file with reproduction steps?

**Comment by averikitsch** [comment]
Closing. Feel free to reopen.
